# Generated by Django 3.2.6 on 2021-08-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='imagenes')),
                ('contentenido', models.TextField()),
                ('fecharegistro', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
